Vagrant.configure('2') do |config|
  config.env.enable #enable .env use
  config.vm.box = 'azure'
  config.vm.box_url = "https://github.com/azure/vagrant-azure/raw/v2.0/dummy.box"
  config.ssh.private_key_path = ENV["SSH_KEY_PATH"]

  # add install script:
  # config.vm.synced_folder "../contents", "/vagrant", type: "nfs"
  config.vm.provision "file", source: "../contents/install.sh", destination: "../vagrant/install.sh"
  # copy pub and priv keys (for some reason the path is different to achieve the same result)
  config.vm.provision "file", source: ENV["SSH_KEY_PATH"], destination: "../#{ENV["ABS_KEY_PATH"]}"
  config.vm.provision "file", source: ENV["SSH_PUB_KEY_PATH"], destination: "../#{ENV["ABS_PUB_KEY_PATH"]}"

  config.vm.define "worker" do |azure|
    azure.vm.provider :azure do |azure, override|
      azure.tenant_id = ENV["AZURE_TENANT_ID"]
      azure.client_id = ENV["AZURE_CLIENT_ID"]
      azure.client_secret = ENV["AZURE_CLIENT_SECRET"]
      azure.subscription_id = ENV["AZURE_SUBSCRIPTION_ID"]

      azure.instance_ready_timeout = 600
      azure.vm_image_urn = 'canonical:ubuntuserver:16.04-LTS:latest'
      # azure.resource_group_name = 'soac-vagrant'
      # azure.vm_name = 'soac-worker'

      override.vm.synced_folder ".", "/vagrant", disabled: true
    end

  # config.vm.provision "shell", inline: "echo Hello, World"
  azure.vm.provision "shell", inline: <<-SHELL
  echo -e "\nInstall vagrant and all required extensions\n"
  cd "../vagrant/"
  mkdir "build" # use for temp storage of files
  touch $HOME/.hushlogin # disable welcome message to allow easy pull of ips
  export SSH_KEY_PATH=ENV["REL_KEY_PATH"]
  chmod +x "install.sh"
  sh "install.sh"
  # rm *.deb
  # rm "install.sh"
  echo -e "\nInstall complete\n"
  SHELL
  end
end
