os: linux
dist: bionic
language: skip
services:
- docker
addons:
    apt:
        packages:
            - sshpass
before_install: skip
install:
- docker --version
stages:
- deploy_hospital1
jobs:
  include:
  - stage: deploy_hospital1
    name: build and deploy services related to hospital1
    script: |
    - export SSHPASS=$WORKER_KEY
    - sshpass -e scp -o "StrictHostKeyChecking no" [FILE] ${WORKER_USER}@${WORKER_IP}:/vagrant/build
      
    - ""
  - stage: deploy
    name: deploy new version
    install: skip
    before_script:

    - sshpass -e scp -o "StrictHostKeyChecking no" remote_files/docker-compose.yml ${MT_USER}@${MT_SERVER}:/vagrant/
    - sshpass -e scp -o "StrictHostKeyChecking no" remote_files/prometheus.yml ${MT_USER}@${MT_SERVER}:/vagrant/
    script: |
      ssh -o "StrictHostKeyChecking no" ${MT_USER}@${MT_SERVER} \
      "cd /vagrant && \
      echo DB_PASSWORD=${DB_PASSWORD} > .env && \
      docker-compose down && \
      docker-compose pull && \
      docker-compose up -d"
