---
- hosts: localhost
  gather_facts: yes
  become: yes
  vars:
    NODEJS_VERSION: "8"
    ansible_distribution_major_version: "7" #trusty
  tasks:
    - name: install git
      yum:
        name: git
        state: present
        update_cache: yes
    - name: Install EPEL repo.
      yum:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm
        state: present
    - name: Import EPEL GPG key.
      rpm_key:
        key: /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}
        state: present
    - name: install nvm
      yum:
        name: npm
        state: present
    - name: Install nodejs
      yum:
        name: nodejs
        state: present
    - name: Get stuff from git
      git:
        repo: https://github.com/sebastiannicolajsen/soac-prototype.git
        dest:  src/
