---
- hosts: localhost
  gather_facts: yes
  become: yes
  vars:
    NODEJS_VERSION: "8"
    ansible_distribution_major_version: "7" #trusty
  tasks:
    - name: Install EPEL repo.
      yum: # should probably check the key of the project, but im lazy...
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm
        state: present
    - name: Install npm, nodejs and git.
      yum:
        name:
          - git
          - npm
          - nodejs
        state: present

    - name: Install pm2 the hacky way, and the "right version"
      shell:
        cmd: npm install -g pm2@^3
    - name: Get stuff from git
      git:
        repo: https://github.com/sebastiannicolajsen/soac-prototype.git
        dest:  src/
        version: terraform # get this branch
