Vagrant.configure("2") do |config|
    config.env.enable #enable .env use
    config.vm.box = 'digital_ocean'
    config.vm.box_url = "https://github.com/devopsgroup-io/vagrant-digitalocean/raw/master/box/digital_ocean.box"
    config.ssh.private_key_path = ENV["WORKER_PRIVATE_KEY_PATH"]

    # add install script:
    config.vm.synced_folder "contents", "/vagrant", type: "rsync"

    config.vm.define "worker" do |droplet|
      droplet.vm.provider :digital_ocean do |provider, override|
	       provider.ssh_key_name = ENV["WORKER_PRIVATE_KEY_NAME"] # <--!
	       provider.token = ENV["DIGITAL_OCEAN_TOKEN"] # <--!
	       provider.image = 'ubuntu-18-04-x64'
	       provider.region = 'nyc1'
	       provider.size = 's-1vcpu-1gb'
      	 override.nfs.functional = false
    	end
    droplet.vm.hostname= "worker"
    droplet.vm.provision "shell", inline: <<-SHELL
    echo -e "\nInstall vagrant and all required extensions\n"
    cd "../vagrant/"
    chmod +x "install.sh"
    sh "install.sh"

    echo -e "\nInstall complete\n"
    SHELL
    end
end
