Vagrant.configure("2") do |config|
    config.env.enable #enable .env use
    config.vm.box = 'digital_ocean'
    config.vm.box_url = "https://github.com/devopsgroup-io/vagrant-digitalocean/raw/master/box/digital_ocean.box"
    config.ssh.private_key_path = ENV["SSH_KEY_PATH"]

    # add install script:
    config.vm.synced_folder "contents", "/vagrant", type: "rsync"
    # copy pub and priv keys (for some reason the path is different to achieve the same result)
    config.vm.provision "file", source: ENV["SSH_KEY_PATH"], destination: "../#{ENV["ABS_KEY_PATH"]}"
    config.vm.provision "file", source: ENV["SSH_PUB_KEY_PATH"], destination: "../#{ENV["ABS_PUB_KEY_PATH"]}"

    config.vm.define "worker" do |droplet|
      droplet.vm.provider :digital_ocean do |provider, override|
	       provider.ssh_key_name = ENV["PROVIDER_KEY_NAME"] # <--!
	       provider.token = ENV["PROVIDER_TOKEN"] # <--!
	       provider.image = 'ubuntu-18-04-x64'
	       provider.region = 'nyc1'
	       provider.size = 's-1vcpu-1gb'
      	 override.nfs.functional = false
    	end
    droplet.vm.hostname= "worker"
    droplet.vm.provision "shell", inline: <<-SHELL
    echo -e "\nInstall vagrant and all required extensions\n"
    cd "../vagrant/"
    mkdir "build" # use for temp storage of files
    touch $HOME/.hushlogin # disable welcome message to allow easy pull of ips
    export SSH_KEY_PATH=ENV["REL_KEY_PATH"]
    chmod +x "install.sh"
    sh "install.sh"
    rm *.deb
    rm "install.sh"
    echo -e "\nInstall complete\n"
    SHELL
    end
end
